# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: none
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev_db
      PGDATA: /var/lib/postgresql/data_test

  adminer:
    image: adminer
    restart: none
    ports:
      - 8080:8080